version: '3.1'

services:
    app:
        build: .
        ports:
            - 3000:3000
        env_file: .env
        environment:
        - APP_HOST=$APP_HOST
        - APP_PORT=$APP_PORT
        - POSTGRES_HOST=$POSTGRES_HOST
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_DATABASE=$POSTGRES_DATABASE

    db:
        image: postgres
        restart: always
        env_file: .env
        environment:
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - 8080:80
        env_file: .env
        environment:
            PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
            PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD

volumes:
    pgdata: {}